# Generated by Django 4.0.3 on 2022-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboardapp', '0002_strloc_v_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.TextField()),
                ('Valuation_Type', models.CharField(blank=True, max_length=150, null=True)),
                ('Price', models.FloatField(max_length=100)),
                ('Last_Change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Part_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Vendor', models.CharField(max_length=100)),
                ('Material', models.TextField()),
                ('Material_description', models.TextField()),
                ('Vendor_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Vendor_description', models.TextField()),
                ('Quota_Valid_from', models.DateField()),
                ('Quota_Valid_to', models.DateField()),
                ('Quota_percentage', models.CharField(max_length=50)),
                ('Quota_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Proctype', models.TextField()),
                ('Spl_Proc_Type', models.TextField()),
                ('Bulk_Ind', models.CharField(max_length=100)),
                ('MRP_Cntrl', models.CharField(max_length=50)),
                ('Buyer', models.CharField(max_length=50)),
                ('Lead_Buyer', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('Bulk_Part', models.TextField()),
                ('Str_loc', models.TextField()),
                ('Vendor_location', models.TextField()),
                ('Vendor_state', models.TextField()),
            ],
        ),
    ]
