# Generated by Django 4.0.3 on 2022-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboardapp', '0003_map_part_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead_Buyer', models.TextField()),
                ('Department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRPCn', models.CharField(max_length=50)),
                ('New_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.TextField()),
                ('Group_Lead', models.TextField()),
            ],
        ),
    ]
