# Generated by Django 4.0.3 on 2022-12-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboardapp', '0005_dmldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_master',
            old_name='Quota_Number',
            new_name='Quota_number',
        ),
        migrations.RenameField(
            model_name='vc_master',
            old_name='model',
            new_name='Models',
        ),
        migrations.RemoveField(
            model_name='vc_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vc_master',
            name='vc_number',
        ),
        migrations.AddField(
            model_name='vc_master',
            name='VC',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
