# Generated by Django 4.0.3 on 2022-12-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboardapp', '0006_rename_quota_number_part_master_quota_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vc_master',
            name='Dom_Exp',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vc_master',
            name='Models',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vc_master',
            name='Type_of_vehicle',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vc_master',
            name='VC',
            field=models.TextField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vc_master',
            name='sub_model_group',
            field=models.TextField(max_length=150),
        ),
    ]
